### ISSUE TITLE
Improve Development Workflow

### ISSUE THREAD

**Issue by alanbsmith** [alanbsmith/react-retro-sockets#3]
### ISSUE OVERVIEW
Currently, the dev workflow is really poor. If you make any change to the JS that is in anyway related to websockets (most things), you have to run `postinstall` and start the server with `node server.js`.

The reason for this behavior is that in development, the webpack dev server uses a 'ghost' express server behind the scenes to run the app. This ghost server doesn't have access to the websocket functionality that lives in `server.js`.

### WHY SHOULD THIS BE A THING?
 The current setup _really_ slows down dev time and increases fatigue. Not a great combo.

### SUGGESTED SOLUTION
I feel like there _should be_ a way for the dev server to EITHER: have access to `server.js` OR: add websockets to the dev server (which is using socket.io already behind the scenes). Definitely open to ideas on this.

**Comment by cdownard** [comment]
On this topic I think we should initialize git flow as well. Right now there's only a `master` branch and we're going to want to have a develop (staging) branch. Releases go into master, hotfixes are branched from master and merged back into first then closed and backmerged into develop, and all new feature branches are branched from develop and merged back into develop (therefore staging). At any give time, develop should represent a stable state ready to be pushed to master. A new release branch is initiated from the develop branch.

For more information on git flow see the following:

[A successful git branching model](http://nvie.com/posts/a-successful-git-branching-model/)
[Git Flow](https://github.com/nvie/gitflow)

On the server side of things, is this something that a script could somehow solve with a watch? The server startup is quite fast. I haven't looked into this yet but it seems like hot reloading the js solves this but I guess that can't be true for the server side socket stuff.

**Comment by alanbsmith** [comment]
this issue was handled with this commit: 7f688d4
