### ISSUE TITLE
Persisting Data

### ISSUE THREAD

**Issue by alanbsmith** [alanbsmith/react-retro-sockets#9]
### ISSUE OVERVIEW
Currently, the site persists all the information in the client session, but if you refresh it's all gone and there's no way to get it back. It would be nice to persist that data to an api/db or maybe just exporting it to a csv or excel doc.

### WHY SHOULD THIS BE A THING?
Allowing groups to look at previous boards, by storing or exporting that info will allow them to reflect on their previous problems, questions, goals, etc. and make forward progress.

### SUGGESTED SOLUTION
to be continued.

**Comment by cdownard** [comment]
This means we get to discuss data flow which means flux choice. Redux pretty please? I'll do all the legwork :D :D

Also, we could add in immutable. Just a thought. If we're going to go the immutable route we should start there though.

**Comment by alanbsmith** [comment]
Agreed. I think Redux is the right choice for where this is heading. The amount of state it will need to keep track of seems to be pointing that direction.

And I'm good with ImmutableJS. I think it enforces best practices for React that aren't a part of JavaScript's nature. If we didn't use ImmutableJS, I think we would find ourselves trying to ad hoc enforce its principles anyway.

**Comment by alanbsmith** [comment]
i think a good approach for this might be moving existing functionality over to Redux / Immutable, and then adding additional functionality (most likely adding multiple boards/rooms/teams whatever).

**Comment by cdownard** [comment]
[A Sails App demo](https://github.com/cdownard/sails-retro-sockets) 

I changed the data model to be a 'note' instead of a post it. I can change it back. Naming conventions just looked weird in sails since it generated Post_it.js as the model and I was like...well until I figure out how to work this I can't stand that casing (neurotic). So in this app they're currently called notes. :fearful:

**Comment by alanbsmith** [comment]
I like the name 'Note' better than 'Post_it' for sure. The original concept was meant to mimic our 'post-its on a  whiteboard' retrospective process (hence the Board name as well). I'm happy to rethink how things are named as we go along.

My main question here is whether separate client / server apps make sense if it's all in JS anyway. Separating rails and node provides a lot of flexibility (at the cost of some complexity), but maybe we're not gaining that much by separating Sails and React? Going to putz around with this today and get familiar with Sails.

Thanks for spiking this out!

**Comment by cdownard** [comment]
http://waterlock.ninja/

Check this out. It's on top of passport. Talk about low barrier to entry.

**Comment by cdownard** [comment]
https://github.com/balderdashy/sails/issues/3429#issuecomment-165004024

Sigh.

**Comment by alanbsmith** [comment]
bummer. so maybe not sails then. I've heard good things about [Hapi](http://hapijs.com/) though, I've never used it myself. [Koa](http://koajs.com/) seems to be popular too, but it looks pretty minimalist (maybe not what we need for the long run).

I'm also still fine with doing a Rails implementation, as I know I can put something together really fast and _know_ that it works.

**Comment by alanbsmith** [comment]
this was resolved with adbc07a44f250c22d9237e3aa0ef16996105ed04
